### RECEBA 10 INFORMAÇÕES DE CADASTRO PESSOAL E INFORME UM RELATÓRIO COM AS INFORMAÇÕES EM UM ÚNICO PRINT

### CALCULE A AREA DE UM TRIANGULO FORNECENDO SOMENTE BASE E ALTURA

### CRIE UM ALGORITIMO CAPAZ DE CALCULAR O DELTA DA FORMULA DE BASCARA

